import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faAppleWhole,
  faAward,
  faBoxOpen,
  faBullseye,
  faCertificate,
  faClipboardCheck,
  faCogs,
  faEnvelope,
  faEye,
  faGem,
  faHandshake,
  faHeart,
  faHospital,
  faImages,
  faLeaf,
  faLemon,
  faMoon,
  faMortarPestle,
  faNewspaper,
  faRocket,
  faSeedling,
  faShieldHalved,
  faStar,
  faThLarge,
  faTrophy,
  faUserTie,
  faVideo,
  faWheatAwn,
} from "@fortawesome/free-solid-svg-icons";

/** Maps HTML `fa-*` class suffix to Font Awesome 6 icon definition */
export const iconByFaClass: Record<string, IconDefinition> = {
  "fa-seedling": faSeedling,
  "fa-wheat-awn": faWheatAwn,
  "fa-mortar-pestle": faMortarPestle,
  "fa-apple-whole": faAppleWhole,
  "fa-lemon": faLemon,
  "fa-shield-halved": faShieldHalved,
  "fa-clipboard-check": faClipboardCheck,
  "fa-moon": faMoon,
  "fa-leaf": faLeaf,
  "fa-hospital": faHospital,
  "fa-award": faAward,
  "fa-certificate": faCertificate,
  "fa-handshake": faHandshake,
  "fa-cogs": faCogs,
  "fa-rocket": faRocket,
  "fa-eye": faEye,
  "fa-video": faVideo,
  "fa-th-large": faThLarge,
  "fa-star": faStar,
  "fa-newspaper": faNewspaper,
  "fa-trophy": faTrophy,
  "fa-gem": faGem,
  "fa-images": faImages,
  "fa-bullseye": faBullseye,
  "fa-heart": faHeart,
  "fa-user-tie": faUserTie,
  "fa-box-open": faBoxOpen,
  "fa-envelope": faEnvelope,
  "fa-diamond": faGem,
};

export function getFaIcon(className: string): IconDefinition {
  const icon = iconByFaClass[className];
  return icon ?? faGem;
}
